---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./calibre2/ks.yaml
  - ./filebrowser/ks.yaml
  #- ./stash/ks.yaml
  #- ./stash2/ks.yaml
