apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:eQSZl+79fVJwUhgZB2/0w+tEcMIjWXwu1Q==,iv:4/HuwRYoZH8jZhw1y2dmhUcGNSB1axTMpSL2KCGSmcc=,tag:1JYcCVV3a+07HSY4lq0DpA==,type:str]
sops:
  age:
    - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzV1NYdmg3L01ERDRkM1gv
        UmhJUy9YNGlWTENrb05IZzNWRnY5RlVHK3dnCkxyOUhtM29EQlBpaVV5YTQvV0dw
        NzNiTWhmT1lZSXd4ejk5dHZCNmxnVVUKLS0tIGJ2VjlBYTAvNFhxQ0d0VTdWMjBP
        VE8vZTJsL0dYYkp6WDRMWHp3QnlsVzQKm4vazIaIEFZO7quYlVb+ucnXO0iRF0pI
        F5/qCz3B1pUhjJ8/Kv1RomUCuJBYwlInW4SbyBqtcZ83PC9vBAAvUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-09T22:45:13Z"
  mac: ENC[AES256_GCM,data:eIOze3Zwxa/dtVzka6tZOxdxTcAmynJb4XxBrWpMnamsAO1nyDXYc5SgVk8JMy4Bcavd4XB0rQiGmdBTf7UryoAMGWhrGSQHJq/yL0T7Xdq6rDh6W0n4UvK/dEZ0Es0bfKfiBWeQz8nLysv5SJSmkRQLHTA92yuU2iIihBTffkE=,iv:+p6Z2bf0FmhOXBW7MO6EOMzMXkpaEpmWZYnpkqKRkS4=,tag:OI+QhTTqhO6Ygwd9PIXfHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
