apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:7v+nUmUlt6S/WoL24X7ONEJU1w9EBJUxGxA8tGtZ8YWy662jeg0ywg==,iv:C++Hl2cb4+hjcCdTP+Z8G2qzU0O+/CMdWq/r3Zc23AA=,tag:kWpYA0/UUAL9kRZmPOfhAQ==,type:str]
sops:
  age:
    - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZk43UWNaa3pncy9UeHdz
        RVJzdC9aeVM1aTkrOWdONnllRURzRUFNNWdjCksvakM5ZUxMaGpUN1lHcTdsdDBw
        VThjUnRocDE4aHB6WjN4UDFRRFMxWW8KLS0tIFNrMTB3c0NMZitaTFlKYVhVRVZN
        dmFodnZtSWYyVU9Wbm5YbmVpYXNTLzAKCnMWposzEVCH3Jco3XyhHPpH/z2dgeJC
        YPZC/Dr0k7KFNB8OxFtT66pOVcD9fYppKif5F6xagRBeOpkRYqgNiA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T22:47:55Z"
  mac: ENC[AES256_GCM,data:0yUSYi+5tnJQawwuPiHE1EEtL2pWtLyIpdo9/pLxQOjf7p+aSt2LqWxAJ/DqmTMEwdXAtDQ+foEbFJ+jogu/RCu9kXdrH54zNDXROfc3zkSRaFtu1zbe0N6GRsQ3qu/EwJF3O9JGRoThD0kePhsg+GEJrq3AD2Rf3tJFVaDimd4=,iv:5JGt93R8OZmwGTDJS8SMEucDwF90Fhf9x6iaQ9mkYpo=,tag:+j45DVyyNiJremtDojoWUw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
