---
# yaml-language-server: $schema=http://schema.301401.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: publish-k8s-schemas-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: publish-k8s-schemas-secret
  data:
    - secretKey: CLOUDFLARE_ACCOUNT_ID
      remoteRef:
        key: SCHEMA_CLOUD_ID
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: SCHEMA_CLOUD_KEY
