---
# yaml-language-server: $schema=https://schema.maverickd650.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: haos-external
  annotations:
    gatus.home-operations.com/endpoint: |
      client:
        dns-resolver: tcp://${UNIFI_HOST}:53
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  hostnames: ["ha.${SECRET_DOMAIN}"]
  rules:
    - backendRefs:
        - name: haos-external
          port: 80
