---
# yaml-language-server: $schema=https://schema.maverickd650.dev/notification.toolkit.fluxcd.io/provider_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-status
spec:
  type: github
  address: https://github.com/MaverickD650/home-operations
  secretRef:
    name: github-status-token-secret
