apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:23RiU196b8c=,iv:z8eqg610Fkn4uvRs7x+SOedLrTkqZcFe1GRe21ydOdI=,tag:t2T9a0Ijg1rojG5tv6BhwQ==,type:str]
sops:
  age:
    - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRc0NVVzhmUC9SK1FIeDZM
        WnN3UVdhMWxJWkw2dlBrRWltcGltZHNGM0N3CmJXUEtmYVpzTElqK0Vyd0tuKzRv
        ZGE2WVdkM0pzUlJwWStxdkJvNm50VnMKLS0tIE1EOVhuRDJDdEtxdDlaQ2Vpcy9N
        c242VDE2K1FEb0I4bGFGQjBOVDhwb1kKwzpk0lwJBlPiJDn0fg8CawxAxuA16X7g
        ZpUAdAJA7hbCmcbrvpruyZfbur94pKGPWLYbsb5IkV4Ie/ChWD6/GQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T22:47:55Z"
  mac: ENC[AES256_GCM,data:sDJlzKgWl/1hOdZj0+xmHsMTwwJcrvBLfz4H0rXawzx+ZBxs6+ffw98RpiqD49kkn3Upuvk6JMFnDZNsoZFCxozhCo1EbcqZfU7YwoOjXSczIrum06eAnB8F7BuXnkhvSwIbgvbqaBOwerk3NYNTlb9aEmiS1f3dJus+EHjuuHw=,iv:sSC/Fio6EM4h/WQ7cLMyoMRBDPPJyLUSWNGkV0KGF4c=,tag:tn4J+tbevjXcFb/Rs1/8Yw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
