---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mend-renovate-app-template-cnpg-main
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": mend-renovate-app-template-cnpg-main
  podMetricsEndpoints:
  - port: metrics
    scheme: http
    tlsConfig:
      ca:
        secret:
          name: mend-renovate-app-template-cnpg-main-ca
          key: ca.crt
      serverName: mend-renovate-app-template-cnpg-main-rw
