apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ocqxFaetkhQagef+rdAkIJCCHZGIhKtdHSEsRjBnTA0=,iv:Yvrw3bNcuTOVQZ6tGZX9nUjohCpFlLx9yv45tRshFZw=,tag:8Ll2OtZ/UbJzur2OVhx0eQ==,type:str]
sops:
  age:
    - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMVRnaUYxU2VHZDUxWng4
        eXRWN1liVkFoQ2x0UzJoRldkaWZKZUJjK2lBCjVkd1Q2UFJ0U3hXSnI1VmtRM0Ux
        M1U0OERqcm9wTitLRWo3eWpDQlk4cFkKLS0tIDZZVmV5WWpHTitHaEhuaGgwQVdF
        SEdjV0FZM3hCTWllMW5JR0hjN0QxWjgKvrDlIrHMNSuBzjTIzWAJMjbcsNdQ8csC
        vMNtFHKcoJsYz5IZ5noQ8snPgXoMVbz91s6NcpAhYdWYeZxlQruOpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T22:47:55Z"
  mac: ENC[AES256_GCM,data:UnLZG7Dz1fvI4xw+BZwFE/LO4qxfJ/s4WneMHhSQqJiv7DTVBfDG7IrR5OAE0bO3Ie3L0vhbQLuvzZX7/uNQGiI9WH74rUIQlTIXovIyvJELMzaw7ubezmsI6R2C1dXw03lftBkBMEfbjmxgEJHJYIJFTR+JYkVt2uGY4r/Bs8M=,iv:QNyHIKm8Fg2MZ+OFJ7ByGagkpHDTUuI9h6H4dLIo5v0=,tag:yPrIdREfjw4CLdIcksdrrw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
