---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  chartRef:
    kind: OCIRepository
    name: renovate-operator
  interval: 30m
  values:
    fullnameOverride: renovate-operator
    config:
      defaultJobBackoffLimit: 5
      defaultJobActiveDeadlineSeconds: 900
    route:
      enabled: true
      hostnames:
        - renovate.${SECRET_DOMAIN}
      parentRefs:
        - name: envoy-internal
          namespace: network
          sectionName: https
    webhook:
      enabled: false
      route:
        enabled: true
        hostnames:
          - renovate-webhook.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
