apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
stringData:
  GFAUSER: ENC[AES256_GCM,data:65h2tIU=,iv:0/BzLcbuDxStnZcQE717F/jaidHmARsXV167b5faKRQ=,tag:RPE5m/pwoAg1lXjkE4ok2Q==,type:str]
  GFAPASSWD: ENC[AES256_GCM,data:3eBeXgrVetONvS6QbwXuSFpWUw==,iv:OVfmjSmePN1KNGVrdcDXFIXcc9Zr//IiBFj40o1OeUk=,tag:vH0CTKek2x4BkRY0/jfbJg==,type:str]
sops:
  age:
    - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUHVIVk5RUWdYbUExRy9V
        R0o5MzM4OTQvWEtMa0ZiYjAvT0w2OE83LzE4CnBjTFlUM2Uxc3RFS3Q3aklRZW5r
        ZG8zM3dleHl4WGVzZGJjRUdxWXhSdTgKLS0tIGlVcG5nenh0WFc2Ym5tZmYzT3Js
        dDFwTkU4RFBhanlYOUxRbTJ5ZlhXSUUKrzqB54RRAxjFLAZrj3PHZm4qK1QiH1Ne
        aR/fiVdcZpzlljWBGzhyvsVTLjJYyoBCkrAq0GGjk9RvGYRnZyeqUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T07:17:03Z"
  mac: ENC[AES256_GCM,data:rzaN4OkeF5j64eXWIYnTnT+kqD5LOZuEYIuwrNQy65IIOtp8i5VuI//1dajl1AiB8v11CTKnuwEjzCT5+TxrKmnqEpuWT/o5EeuC48E2KBopiJOnMNUFdpu5It76kY+TeSIjn+N5j8UBJNX04WQT2MFouj5qftz72PJstRXM7Js=,iv:RPcu1rpyPiGEdGKvcwWhFW0batjFokl8JdoaYmFgADQ=,tag:pWIEbMTNhGEkZGqJjJy4vQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
