apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
stringData:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:sIXLH4L7mJfz2/xWnsPwwiCitw==,iv:dA3fpWq4SyJYD/HmdTWe5tgriemVi5pfD1O/HRjOyWY=,tag:txJ1wBO+PpUJLgVh0kpipQ==,type:str]
    client-id: ENC[AES256_GCM,data:Vt7T7IPW9VrniU/PxYWPbosTR5/v5lJF5GBblYnAuGV7e6SN,iv:F3vJvs0cCR8fR3dBUAwHb3b1M6rMXccIWefleyQUQ7Y=,tag:sK9E7utDOM2OO9EgKhUjWg==,type:str]
    client-secret: ENC[AES256_GCM,data:RZ2PS3A9GhOaFHzplPVEHSRreZSUrBz4BW7bD3RaTjM=,iv:SRQ1XTBabExDFjn1v32ibU0Xf33aF5HAxnWrP8MrHa8=,tag:OqlvCTPvlytNDw/5n+xkvw==,type:str]
    auth-url: ENC[AES256_GCM,data:rM/sQsMmZci33RM9BzlY5lJF+iklzDGUhZeA+ea49hkc,iv:ZDw6KShWgLgS1jKHmOk82sPQ7EujQYIRrXd7D+CCb0s=,tag:PNRGyAdIJTthC2UbbsZIWw==,type:str]
    token-url: ENC[AES256_GCM,data:vGnRjV1Fa8Yxwzn5Rj260LRKO/zdojoMSbYRuwdkmeC4KstLN6c=,iv:eb1MMTtfj4Up7koq6z96uYK7BYx6LbD8cwMV4Uc4CtQ=,tag:GK+6irh5r4x6BUKPAmc8Hg==,type:str]
sops:
    age:
        - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VnAvUTNMUlpaeEpYMU8r
            MTZIWVpSaFhLNnptOFdKS3RBbHBTYk5uZXdVCnF4YmlWY01ta0NrNjEwTFd4QzNB
            OVF0dWEwYlBzTDJkdlpScHNKN2lZajQKLS0tIENHMTByU2I2RUV2enVoYlh2RDdx
            MnZhekxKUTlFNTBDSVlhVS9HU2srNmcKrHTp7Bg3Q280BpBiuBD5f3XF6j7FP3rf
            8hO2pyH/4kSp6GMjvjiyILQhrnLVngWD5QxFXC4BWBT0/obFNJcIBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T21:23:54Z"
    mac: ENC[AES256_GCM,data:+WAksF/2qJMC7I1qzhVbRYRb3RX0Cl1a2MSMN+tktZKA7RzFH8IKPSY93kTC15BbmmjeZaUBb2N1DomA+TTLvnO92R1dRb4Ek4ErgNhXJah94ildk6AYaUse+/AIWJPejWIjp8XvVzPJ9smrH7u494oUe0fvaGb1UyZUGNwpk5s=,iv:t+jOtuI1J8WbAedV1G7EzwFntOfVIGaI5oclFC7yd+A=,tag:iC/dGfIgknQTgk53pPoPwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
