apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
stringData:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:sIXLH4L7mJfz2/xWnsPwwiCitw==,iv:dA3fpWq4SyJYD/HmdTWe5tgriemVi5pfD1O/HRjOyWY=,tag:txJ1wBO+PpUJLgVh0kpipQ==,type:str]
    client-id: ENC[AES256_GCM,data:Vt7T7IPW9VrniU/PxYWPbosTR5/v5lJF5GBblYnAuGV7e6SN,iv:F3vJvs0cCR8fR3dBUAwHb3b1M6rMXccIWefleyQUQ7Y=,tag:sK9E7utDOM2OO9EgKhUjWg==,type:str]
    client-secret: ENC[AES256_GCM,data:RZ2PS3A9GhOaFHzplPVEHSRreZSUrBz4BW7bD3RaTjM=,iv:SRQ1XTBabExDFjn1v32ibU0Xf33aF5HAxnWrP8MrHa8=,tag:OqlvCTPvlytNDw/5n+xkvw==,type:str]
    auth-url: ENC[AES256_GCM,data:XfqeTihb7bbiUckc/BMl2g8u/DOlJRUFs7E0d8SL1hPm,iv:/8e85erPZ9LHP4pxGmM8wtKL+qfS+m59dVFp9nLLXgw=,tag:QoF61l06+lrb/d2iVEjq8g==,type:str]
    token-url: ENC[AES256_GCM,data:1S35ma9B2bfKYKVk7F+HT5BatfADUjtSCEqRwfgOv6xJGJmsjew=,iv:5LewfxwFMdXm9TQKchYH+sloghCNufXLmdrZnWpRKFM=,tag:fqvoMHM8ip4EMVLHGWSoGA==,type:str]
sops:
    age:
        - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VnAvUTNMUlpaeEpYMU8r
            MTZIWVpSaFhLNnptOFdKS3RBbHBTYk5uZXdVCnF4YmlWY01ta0NrNjEwTFd4QzNB
            OVF0dWEwYlBzTDJkdlpScHNKN2lZajQKLS0tIENHMTByU2I2RUV2enVoYlh2RDdx
            MnZhekxKUTlFNTBDSVlhVS9HU2srNmcKrHTp7Bg3Q280BpBiuBD5f3XF6j7FP3rf
            8hO2pyH/4kSp6GMjvjiyILQhrnLVngWD5QxFXC4BWBT0/obFNJcIBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T22:43:01Z"
    mac: ENC[AES256_GCM,data:ANOvNqA9rKKEbGSYtV45nT39ZEOYmjkjlipESpKZ314eJBW5Y4eBDvAQmyVbH51ERW/ZplVs616xRNvk9vpnYB3CvUFczq5KkGsF/PBPUNJ9FNQRDTFwZ3UzJ3ASMmf84r192Ro1Oz1H5csMIKzsZigkG+muNXxBQlHoE8XGpl8=,iv:xOJobzF/SpiTPSoysOfuxXXoKm3/4RZ2sgz6P875QAA=,tag:y4vh7MIwXtWftKKYyj5Meg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
