apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:sIXLH4L7mJfz2/xWnsPwwiCitw==,iv:dA3fpWq4SyJYD/HmdTWe5tgriemVi5pfD1O/HRjOyWY=,tag:txJ1wBO+PpUJLgVh0kpipQ==,type:str]
sops:
  age:
    - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VnAvUTNMUlpaeEpYMU8r
        MTZIWVpSaFhLNnptOFdKS3RBbHBTYk5uZXdVCnF4YmlWY01ta0NrNjEwTFd4QzNB
        OVF0dWEwYlBzTDJkdlpScHNKN2lZajQKLS0tIENHMTByU2I2RUV2enVoYlh2RDdx
        MnZhekxKUTlFNTBDSVlhVS9HU2srNmcKrHTp7Bg3Q280BpBiuBD5f3XF6j7FP3rf
        8hO2pyH/4kSp6GMjvjiyILQhrnLVngWD5QxFXC4BWBT0/obFNJcIBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-15T21:35:56Z"
  mac: ENC[AES256_GCM,data:lA+UPbLd3w7i7ITw7Ecgld6sYNwYwqq/B0/VHGtRs9WcnHchaV4YTdw6bZ9i6Is+8pipXyYhD8OfK3MZy/+oBWtzn6UgnygbOCvfHaaUPiwHb4k60Zo3EPVZbpDDiFPk54Y/BrPh0a/OqqOz5yma2nGVzILPbTOpXp9vii3u/Hg=,iv:nPgaeTYIwSghcJ0Ln+I8N3QiwlEQA3wR+ds9yLQBzz0=,tag:RxhvRL2ftGw1rsJoGMdy9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
