apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
stringData:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:sIXLH4L7mJfz2/xWnsPwwiCitw==,iv:dA3fpWq4SyJYD/HmdTWe5tgriemVi5pfD1O/HRjOyWY=,tag:txJ1wBO+PpUJLgVh0kpipQ==,type:str]
    client-id: ENC[AES256_GCM,data:Vt7T7IPW9VrniU/PxYWPbosTR5/v5lJF5GBblYnAuGV7e6SN,iv:F3vJvs0cCR8fR3dBUAwHb3b1M6rMXccIWefleyQUQ7Y=,tag:sK9E7utDOM2OO9EgKhUjWg==,type:str]
    client-secret: ENC[AES256_GCM,data:RZ2PS3A9GhOaFHzplPVEHSRreZSUrBz4BW7bD3RaTjM=,iv:SRQ1XTBabExDFjn1v32ibU0Xf33aF5HAxnWrP8MrHa8=,tag:OqlvCTPvlytNDw/5n+xkvw==,type:str]
    auth-url: ENC[AES256_GCM,data:rtIknZqkJSjpaei1Kk6Iv2Ojg83NMA9SsSqBWtBWA3Y+KWURpmTBN6YIoNqDWBPqsIkDBm8=,iv:Gq902f3Id/iL+OzQx0U3WnztO/cVjyGlioSdv5kZGEE=,tag:iDf8eYwBmo3Xbs+AJs8SSA==,type:str]
    token-url: ENC[AES256_GCM,data:b0QcADe8Wjhw1gPFzMkLb9vFGV7lhlI7g3PvcAvEQF51NGMLyhOlSbBXKT7gd4yWHI3D3QaUCRRHxw==,iv:0YAqbpxFljk5uQy9TZEKYAahVijmwfLOEKM1pG7bVE4=,tag:+EmfyWY7pJ4oR+hM6JMo5w==,type:str]
sops:
    age:
        - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VnAvUTNMUlpaeEpYMU8r
            MTZIWVpSaFhLNnptOFdKS3RBbHBTYk5uZXdVCnF4YmlWY01ta0NrNjEwTFd4QzNB
            OVF0dWEwYlBzTDJkdlpScHNKN2lZajQKLS0tIENHMTByU2I2RUV2enVoYlh2RDdx
            MnZhekxKUTlFNTBDSVlhVS9HU2srNmcKrHTp7Bg3Q280BpBiuBD5f3XF6j7FP3rf
            8hO2pyH/4kSp6GMjvjiyILQhrnLVngWD5QxFXC4BWBT0/obFNJcIBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T21:44:27Z"
    mac: ENC[AES256_GCM,data:9WycLfyvQcU420qHdzRMAEjYd9hSCG5xCXiwcsakI7/yt0Qb5JEYttt4f23THcf79myytyjuAJc4Zh38eMfzp5KoUYgg39AvfoNPGF6ndwSl3xRs5lbQ0SOcT1ntQ57rNve/KbO2IIRuoLTTZk75EnIPh0JFXAQ5UlCrLPv6G84=,iv:l8E1fqcBM4X9I1/jR+sP8eo8GnJBCN+GfljNHvUgiiA=,tag:R4zRBbPpD5HKjL04lwA5Gw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
