apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:KlBeHi4=,iv:7lQIB1lphQVqB3nAiEcjV//vpp6ouS4i5tBaiFC5kC8=,tag:PfrYZ+X/Lpd6k1xOh5jI8w==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:ScUvKw786guWD5RE7cOwF+gTUQ==,iv:26Aw9MFdGXUSwnZH32wNrNMEs3fXU3tggZTLrnS4pW8=,tag:+r1UhVzpArEGBs7Ar0F4VA==,type:str]
sops:
    age:
        - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUHVIVk5RUWdYbUExRy9V
            R0o5MzM4OTQvWEtMa0ZiYjAvT0w2OE83LzE4CnBjTFlUM2Uxc3RFS3Q3aklRZW5r
            ZG8zM3dleHl4WGVzZGJjRUdxWXhSdTgKLS0tIGlVcG5nenh0WFc2Ym5tZmYzT3Js
            dDFwTkU4RFBhanlYOUxRbTJ5ZlhXSUUKrzqB54RRAxjFLAZrj3PHZm4qK1QiH1Ne
            aR/fiVdcZpzlljWBGzhyvsVTLjJYyoBCkrAq0GGjk9RvGYRnZyeqUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T22:24:19Z"
    mac: ENC[AES256_GCM,data:b3lhzM2o64G+EJCil+MiuSHCyizh7cE+sfLg627Hqz4RcNyJIZhNfR/7mVBW8HQhgIHiGIPITu7znlnurXq2wLZK/vFCHK7hljYELOAfCPT775AKF+KoORl9SwwkKgtMxAZysWTtKtlhMzF4R+PlQuY60X5SqtDFTyR3y21anAA=,iv:KaqiMcp02cPNnU0dOgE/gQ4Ysa6Iv9J0OnZp2BAoXS8=,tag:LBy/6W5cF13jIrBSn7vGHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
