apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
stringData:
  address: ENC[AES256_GCM,data:2HtscLJxIs5TNf7ng7icnuRyJYaUl+dZoOYg9X+sDk7ksr8oIzgAlB0tEbmVhdHSgqRdrObB44jPuqcUdkFVfV77eDltoQzTrsamCeeWukETG8/fYQu4gB9qp5ehgop9HsnSCMCxJsFBP/p1fHgJ+u7q/3yQV1HLCA==,iv:kE7hxR6ACvVg6vvR0KUUC0p9GKwuYERcm9O+S5PCa28=,tag:SNS9aJ6Kxo3s6KrZVp0hfQ==,type:str]
sops:
  age:
    - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Z3R0djRGczRsdDI5c3BP
        clVYWXlxZkNjN1pGUi9qTk1zaFNiOGh6b1NrCldydGlxaG9LZlRyZS9lL3Rhemkz
        azNiMlB0aUZ1WktpZ2t4LzBDeWgyZU0KLS0tIDdDMEhtK0JvbFNQV2EzcEhNZ2xv
        T1Q0b3phN1FaTm1CdHVxeWZHM0xNeGcKEljaYbYCTlXe2yQGfZmKn5vnoe7BiC5Z
        ly9NTaYe9kTXizMdef3MgRivfq3XE9iu6Rln5nZWE0NEJPKAa1ARqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T21:20:56Z"
  mac: ENC[AES256_GCM,data:cwohOD5h0r/pFmON8S0ECjrfefClPSbShv9xtqcywsbMfekMvX7vbejcR/0rgSXvD3Pbs0tOldB8cB2LuGoM9NjvCXOwwpZTc+dEfcLWHoZe6dQtaSwjxgMjeoyWUsJ2K2JFhZ5s4GxwPlUdbNir1f6nHQFKBmXZXl58/8B0rqE=,iv:IyBR0I7uS4Yr453O6pBE+A75pfI8xF4y+TSNVzm1bHQ=,tag:apl5HZqcDlzlGPgNKN0k0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
