---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jobs

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./publish-k8s-schemas/ks.yaml
