---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./echo/ks.yaml
  - ./freshrss/ks.yaml
  - ./homepage/ks.yaml
  - ./linkwarden/ks.yaml
  - ./mealie/ks.yaml
  #- ./mend-renovate/ks.yaml
  - ./snippet-box/ks.yaml
  - ./renovate-operator/ks.yaml
