---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./echo/ks.yaml
  - ./freshrss/ks.yaml
  - ./homepage/ks.yaml
  - ./mend-renovate/ks.yaml
