---
# yaml-language-server: $schema=https://schema.301401.xyz/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: snippet-box
  annotations:
    gatus.home-operations.com/endpoint: |
      client:
        dns-resolver: tcp://${UNIFI_HOST}:53
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  hostnames: ["snippet.${SECRET_DOMAIN}"]
  rules:
    - backendRefs:
        - name: snippet-box
          port: 5039
