apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:wZja4raa8yUD/QAxQuqWjLdj9ZQ+GK27xsxrzWk8HUYRIgFMERqQbbp37U9h66qC6iP/Z1NVyZ35U+iKRZEqXMlpU5b+LECASFO679/KrShTflmxZechrip9vLvOfz6C3AmxMBh99XU272BuvniaF4/QWc6NWK7tSKSeTomus143ny7+aWkvzBbvwkebz3E03WiWTFdgTOMIFZT4359njaLelPd2JpdQwJcEjrAcwHjVMr+4,iv:sndm8KzHL7d+PT0doKt1N1r0/l5Yp7mtgNQGt0blTOE=,tag:TjeUnNAe5+qVBdfqFr7sLA==,type:str]
sops:
  age:
    - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYlc2Zk5EcjBQRXNTUkRw
        eGIxbWNoVmJ6dHZkQ2FXd2pLd0Exa2VDMVVNCnBpU2ZCWlg4UEt2OEJVMytqQWZl
        eEFjWW93dm4wU0pGTmFveXNGLzdNQ3cKLS0tIHRoQzN5U1RCWmQ0SllnOHNPVXhT
        bjZmK0JrWE1scUlEeEJWMVBvSmlPelEKlnfXCBUqDNnqY5+5QEV65U9XaJnS7Vvg
        JQtA8XsLhEUOdkK0C3D7OGTRUGxANsVhaOhTYGyciomHzalmXHpt3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T22:47:55Z"
  mac: ENC[AES256_GCM,data:rLOAQmjwH++sMI9Rzqd/98ZzHfPkd4XfWIGpy7nBVVs5ms+rbcMfCMIPnKUb3y3gub/6jtDDPejOPkmXi9TLEUf2HX7P759OXHpT9nwt2RyWmPTAlGke1tamvWkrspkObnlVh0OPuToRBGYqs5bi107yV2RZdvvRWGP00KZc/wU=,iv:sSWUW8zladimF+r0fS75E65euus5Nfyl0xxLn0440qk=,tag:a4/S0zPnzamxiv+1ZqcPHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
