---
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: mavbot-auth-token
spec:
  appID: "1030599"
  installID: "56169703"
  auth:
    privateKey:
      secretRef:
        name: mavbot-pem # reference secret from step 1.
        key: private_key_pem
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mavbot-auth-token
spec:
  refreshInterval: "30m0s"
  target:
    name: mavbot-home-ops
    template:
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_COM_TOKEN: "{{ .token }}"
        GITHUB_COM_USER: TWF2ZXJpY2s2NTA=
        RENOVATE_TOKEN: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: mavbot-auth-token
---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: home-ops
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  discoveryFilter: maverickd650/home-operations
  extraEnv:
    - name: NODE_OPTIONS
      value: "--dns-result-order=ipv4first"
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: '["pnpm run bundle"]'
    - name: RENOVATE_ENDPOINT
      value: https://api.github.com/
    - name: RENOVATE_PLATFORM
      value: github
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.system.svc.cluster.local:6379"
  image: ghcr.io/renovatebot/renovate:42.85.5
  parallelism: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 2Gi
  schedule: 0 * * * *
  secretRef: mavbot-home-ops
  webhook:
    enabled: true
    authentication:
      enabled: false
