apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.js: |
    module.exports = {
      platform: 'github',
      cacheDir: '/cache/renovate',
    };
---
# yaml-language-server: $schema=https://schema.maverickd650.dev/generators.external-secrets.io/githubaccesstoken_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: mavbot-auth-token
spec:
  appID: "1030599"
  installID: "56169703"
  auth:
    privateKey:
      secretRef:
        name: mavbot-pem # reference secret from step 1.
        key: private_key_pem
---
# yaml-language-server: $schema=http://schema.maverickd650.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mavbot-auth-token
spec:
  refreshInterval: "30m0s"
  target:
    name: mavbot-home-ops
    template:
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_COM_TOKEN: "{{ .token }}"
        GITHUB_COM_USER: TWF2ZXJpY2s2NTA=
        RENOVATE_TOKEN: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: mavbot-auth-token
---
# yaml-language-server: $schema=https://schema.maverickd650.dev/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: home-ops
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  discoveryFilter: maverickd650/home-operations
  extraEnv:
    - name: RENOVATE_CONFIG_FILE
      value: /config/config.js
    - name: RENOVATE_PERSIST_REPO_DATA
      value: "true"
    - name: RENOVATE_REPOSITORY_CACHE
      value: "enabled"
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: '["pnpm run bundle"]'
    - name: RENOVATE_ENDPOINT
      value: https://api.github.com/
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.system.svc.cluster.local:6379"
  image: ghcr.io/renovatebot/renovate:43.34.0
  parallelism: 1
  resources:
    requests:
      cpu: 735m
      memory: 2420Mi
    limits:
      memory: 2420Mi
  extraVolumes:
    - name: renovate-cache
      persistentVolumeClaim:
        claimName: renovate-cache-home-ops
    - name: renovate-config
      configMap:
        name: renovate-config
  extraVolumeMounts:
    - name: renovate-cache
      mountPath: /cache
    - name: renovate-config
      mountPath: /config
  schedule: "@hourly"
  secretRef: mavbot-home-ops
  webhook:
    enabled: true
    authentication:
      enabled: false
---
# yaml-language-server: $schema=https://schema.maverickd650.dev/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: other-repositories
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  discoveryFilter: maverickd650/cluster-docs, maverickd650/feedcord
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: '["pnpm run bundle"]'
    - name: RENOVATE_ENDPOINT
      value: https://api.github.com/
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.system.svc.cluster.local:6379"
    - name: RENOVATE_REDIS_PREFIX
      value: "docs:"
  image: ghcr.io/renovatebot/renovate:43.34.0
  parallelism: 1
  resources:
    requests:
      cpu: 735m
      memory: 2420Mi
    limits:
      memory: 2420Mi
  schedule: "30 */6 * * *"
  secretRef: mavbot-home-ops
  webhook:
    enabled: true
    authentication:
      enabled: false
