---
# yaml-language-server: $schema=https://schema.maverickd650.dev/longhorn.io/recurringjob_v1beta2.json
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-cleanup
spec:
  concurrency: 1
  cron: 0 8 * * *
  groups:
  - default
  name: cleanup
  retain: 0
  task: snapshot-cleanup
