---
# yaml-language-server: $schema=https://schema.maverickd650.dev/longhorn.io/recurringjob_v1beta2.json
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-delete
spec:
  concurrency: 1
  cron: 0 7 * * *
  groups:
  - default
  name: delete
  retain: 0
  task: snapshot-delete
