---
# yaml-language-server: $schema=https://schema.maverickd650.dev/longhorn.io/recurringjob_v1beta2.json
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: trim
spec:
  concurrency: 1
  cron: 0 15 * * *
  groups:
  - default
  name: trim
  retain: 0
  task: filesystem-trim
