---
# yaml-language-server: $schema=https://schema.maverickd650.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: feedcord-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: feedcord-secret
  data:
    - secretKey: DISCORD_RELEASES_WEBHOOK
      remoteRef:
        key: FEEDCORD_DISCORD_RELEASES_WEBHOOK
    - secretKey: DISCORD_HOBBIES_WEBHOOK
      remoteRef:
        key: FEEDCORD_DISCORD_HOBBIES_WEBHOOK
    - secretKey: DISCORD_TECH_WEBHOOK
      remoteRef:
        key: FEEDCORD_DISCORD_TECH_WEBHOOK
