---
# yaml-language-server: $schema=https://schema.maverickd650.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-ext-dns-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: unifi-ext-dns-secret
  data:
    - secretKey: UNIFI_HOST
      remoteRef:
        key: UNIFI_HOST
    - secretKey: UNIFI_API_KEY
      remoteRef:
        key: UNIFI_API_KEY
