apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  unifi-key: ENC[AES256_GCM,data:9rlPnOTVl5G1XpLZmfHzhkkO8/qYOlrPR3tqDs4ZrPg=,iv:1eJswtOpaz7mnB2NlEfRupGanWKVuB1+Sbo8DQmnRR4=,tag:4IAxLGKxuEAdAu5dfOqREw==,type:str]
  unifi-host: ENC[AES256_GCM,data:BTL4gfYHDAEDB44=,iv:gmXD8tNbreJ0VSIvXBe99G8igIivfEASqCSZL9EpCpI=,tag:+4fVEMNiFe1sphMUWSk4pA==,type:str]
sops:
  age:
    - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Y0g5TWdwWVJFL3dhNHd1
        M3IzUTEzNit3UjVwRlBoRGZYNEhKeTJEenpjClE4OExVWkVvODZacXQwRkxhdkND
        UmVIQzlwR291ak9neCtRRExLT3N4elkKLS0tIG55azZIazByeW9oV1dqKzE1c2VQ
        RWJ3V3IxU0ZGZVROZWwyamh1NEFubmsKsjUlEr0BClSyKLm7hDL2OQOcwJyvBX+5
        Tb/B9rAfMLORw+WTBwAR6DYqiHXT9Qjfx9M9+8eoZyuImp3yxBOC0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-30T18:44:56Z"
  mac: ENC[AES256_GCM,data:Yd17/yU3qYAEzPs/e6mFyjWMXuvLHeLVDHK9kLQc7X7A46wSJb3lFN0yXq4LKd94qbscUgM4q8g3jdO4lk1uGtbgG/sca6Gpx5S9CeWYMhe36i1pN2vmYrYk0BLzSTzcyIY1uCahVbx+TvsZM91Vba8Bnyu7SeabWLCp8z0HxOA=,iv:XYfu4ew/36YlVL/EIfNlHfVyL2XW9quMu4GywkqPf4w=,tag:dFcZVeFc507Y3lWYZw0fqg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
