apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns-secret
stringData:
    unifi-key: ENC[AES256_GCM,data:9rlPnOTVl5G1XpLZmfHzhkkO8/qYOlrPR3tqDs4ZrPg=,iv:1eJswtOpaz7mnB2NlEfRupGanWKVuB1+Sbo8DQmnRR4=,tag:4IAxLGKxuEAdAu5dfOqREw==,type:str]
    unifi-host: ENC[AES256_GCM,data:TAMWFa7BRta5kIynGxEQc9mMqQ==,iv:yl6jEPbJsSeESSBvivApsDHXxXNUt4As3FSW8I709Ao=,tag:G0gH6I/Q3MXHbMKwA5VZ1w==,type:str]
sops:
    age:
        - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Y0g5TWdwWVJFL3dhNHd1
            M3IzUTEzNit3UjVwRlBoRGZYNEhKeTJEenpjClE4OExVWkVvODZacXQwRkxhdkND
            UmVIQzlwR291ak9neCtRRExLT3N4elkKLS0tIG55azZIazByeW9oV1dqKzE1c2VQ
            RWJ3V3IxU0ZGZVROZWwyamh1NEFubmsKsjUlEr0BClSyKLm7hDL2OQOcwJyvBX+5
            Tb/B9rAfMLORw+WTBwAR6DYqiHXT9Qjfx9M9+8eoZyuImp3yxBOC0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T22:23:12Z"
    mac: ENC[AES256_GCM,data:pH7pa3ImdVZkH0jvIdRTmflpefmQaAKEtOPsujUVuKFc7WgMDM+EXyddLL/wP2fSmW/rn9hYcENJK9kQxN8V/aIMNU95kKZ+DSsJA7CGxOldyZypU+dfmEK3wz+aHrqExlwkzzI5BhlhLmhtkuK0mf/4COtGdDoa0FNYZZNn1xc=,iv:e5m00O53Gjc1dPJTM+T5SO0GsNijI6E7p2FLcj1QxS8=,tag:5Xn+OWN2L8+qV057FRho8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
