---
alerting:
  discord:
    webhook-url: "${GATUS_DISCORD_WEBHOOK_GLOBAL}"
    default-alert:
      description: "health check failed"
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 2

metrics: true

storage:
  type: sqlite
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/213795
  link: https://github.com/MaverickD650
  buttons:
    - name: Github
      link: https://github.com/MaverickD650
    - name: Homelab
      link: https://github.com/MaverickD650/home-operations

web:
  port: ${GATUS_WEB_PORT}

