---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./clusterissuer.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./postgres.yaml
  - ./prometheusrule.yaml
  - ./secret.sops.yaml
  - ./selfsigned.yaml
