apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:UP9XvaavdtUvkX+iT7yYws5/8gv2Hc/qotqE1vek1wHko8VVdHY2qQ==,iv:PEK9IYK1ik08L+Fm0We5FxxdZaHXrMDKBv/jNBvr+Tw=,tag:DFxTr7u4KGveNV+CaRE7nw==,type:str]
sops:
  age:
    - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NFA2azQxeUczWkZCa044
        cTBNTjV5NVh1eGtiL1VyN0RFd0JKSmtBdFJnCmVjck1CTElwWU1KK1ExaG9KK2ZO
        ektYUlplZEpjbkxwS0F0dXNxQjM0c2MKLS0tIEJhQkRQV09JeGZzcVBtUE9KNTlF
        UXdIZ3lvd1hjR2taM3pJVmkxRU81cGsKSXgjoLcvNUsv+7fIbF/OJeJsNXFBO0E+
        bdsNRjO0f+gjsdhaN4KI/oh7x4k15lPluECoSlHFC9GiGGc/lR5roQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T22:47:55Z"
  mac: ENC[AES256_GCM,data:SOBmkItxBVlofLK8Fn6nlX5I6d5Pt/6Ku54Kjwh4289r4/i6pFpPpMfNdNNX3W7h8eohJP6lRoPks7DjsypQ/kbxRv3gmZ2FvseZo2Xgs2tJhn7nloSX52X4HA79h8wpj/aBogkBKh6F9tY3h+XwwD+FBql4+pGN8+VPz7HJpSQ=,iv:Q0gB8vB6uSfskLkAnsV7CbeuHx5X0Rd2s7HpwGxJkSU=,tag:5sBgFLMvlITFNGca8sWnGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
