---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: unifi-secret
  data:
    - secretKey: UP_UNIFI_DEFAULT_URL
      remoteRef:
        key: UP_UNIFI_DEFAULT_URL
    - secretKey: UP_UNIFI_DEFAULT_API_KEY
      remoteRef:
        key: UP_UNIFI_DEFAULT_API_KEY
