---
# yaml-language-server: $schema=https://schema.maverickd650.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dragonfly
spec:
  selector:
    matchLabels:
      app: dragonfly
  podTargetLabels: ["app"]
  podMetricsEndpoints:
    - port: admin
  fallbackScrapeProtocol: PrometheusText1.0.0
