---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate
      app.kubernetes.io/instance: renovate
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: renovate-operator
      namespace: default
  interval: 1h
  path: ./kubernetes/apps/default/renovate-operator/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator-jobs
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate
      app.kubernetes.io/instance: renovate
  dependsOn:
    - name: renovate-operator
  interval: 1h
  path: ./kubernetes/apps/default/renovate-operator/jobs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  timeout: 5m
  wait: false
