---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./volsync/ks.yaml
  - ./cloudnative-pg/ks.yaml
  - ./tuppr/ks.yaml
