---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  chartRef:
    kind: OCIRepository
    name: flux-operator
  interval: 1h
  values:
    web:
      enabled: true
      config:
        baseURL: https://flux-dashboard.${SECRET_DOMAIN}
        authentication:
          type: OAuth2
          oauth2:
            provider: OIDC
            issuerURL: https://pocket.${SECRET_DOMAIN}
      networkPolicy:
        create: false
    serviceMonitor:
      create: true
  valuesFrom:
    - kind: Secret
      name: flux-webui-oidc
      valuesKey: clientID
      targetPath: web.config.authentication.oauth2.clientID
    - kind: Secret
      name: flux-webui-oidc
      valuesKey: clientSecret
      targetPath: web.config.authentication.oauth2.clientSecret
