---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: homepage-secret
  data:
    - secretKey: HOMEPAGE_VAR_BOOKLORE_USER
      remoteRef:
        key: HOMEPAGE_VAR_BOOKLORE_USER
    - secretKey: HOMEPAGE_VAR_BOOKLORE_PASSWORD
      remoteRef:
        key: HOMEPAGE_VAR_BOOKLORE_PASSWORD
    - secretKey: HOMEPAGE_VAR_CLOUDFLARE_AID
      remoteRef:
        key: HOMEPAGE_VAR_CLOUDFLARE_AID
    - secretKey: HOMEPAGE_VAR_CLOUDFLARE_API
      remoteRef:
        key: HOMEPAGE_VAR_CLOUDFLARE_API
    - secretKey: HOMEPAGE_VAR_CLOUDFLARE_TID
      remoteRef:
        key: HOMEPAGE_VAR_CLOUDFLARE_TID
    - secretKey: HOMEPAGE_VAR_FRESHRSS_USERNAME
      remoteRef:
        key: HOMEPAGE_VAR_FRESHRSS_USERNAME
    - secretKey: HOMEPAGE_VAR_FRESHRSS_PASSWORD
      remoteRef:
        key: HOMEPAGE_VAR_FRESHRSS_PASSWORD
    - secretKey: HOMEPAGE_VAR_GRAFANA_USER
      remoteRef:
        key: HOMEPAGE_VAR_GRAFANA_USER
    - secretKey: HOMEPAGE_VAR_GRAFANA_PASSWORD
      remoteRef:
        key: HOMEPAGE_VAR_GRAFANA_PASSWORD
    - secretKey: HOMEPAGE_VAR_HOMEASSISTANT_API
      remoteRef:
        key: HOMEPAGE_VAR_HOMEASSISTANT_API
    - secretKey: HOMEPAGE_VAR_LATITUDE
      remoteRef:
        key: HOMEPAGE_VAR_LATITUDE
    - secretKey: HOMEPAGE_VAR_LONGITUDE
      remoteRef:
        key: HOMEPAGE_VAR_LONGITUDE
    - secretKey: HOMEPAGE_VAR_LINKWARDEN_API
      remoteRef:
        key: HOMEPAGE_VAR_LINKWARDEN_API
    - secretKey: HOMEPAGE_VAR_MEALIE_API
      remoteRef:
        key: HOMEPAGE_VAR_MEALIE_API
    - secretKey: HOMEPAGE_VAR_PAPERLESS_API
      remoteRef:
        key: HOMEPAGE_VAR_PAPERLESS_API
    - secretKey: HOMEPAGE_VAR_PLEX_API
      remoteRef:
        key: HOMEPAGE_VAR_PLEX_API
    - secretKey: HOMEPAGE_VAR_TRUENAS_API
      remoteRef:
        key: HOMEPAGE_VAR_TRUENAS_API
    - secretKey: HOMEPAGE_VAR_UNIFI_API
      remoteRef:
        key: HOMEPAGE_VAR_UNIFI_API
