---
# yaml-language-server: $schema=https://schema.maverickd650.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: linkwarden-cnpg-main
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": linkwarden-cnpg-main
  podMetricsEndpoints:
  - port: metrics
    scheme: http
    tlsConfig:
      ca:
        secret:
          name: linkwarden-cnpg-main-ca
          key: ca.crt
      serverName: linkwarden-cnpg-main-rw
