apiVersion: v1
kind: Secret
metadata:
  name: universal-auth-credentials
stringData:
  clientId: ENC[AES256_GCM,data:PHKnSJ92IhVOoChOiB/WUsx4gfZeqbj1h81oJwaRQI8q/io5,iv:HUqVsG9E+9rvgJsTw4jgvSYrITXVvih6TdqAl/6EgKI=,tag:+PJfuKVqqaO1uVxowc4Mcw==,type:str]
  clientSecret: ENC[AES256_GCM,data:usgliKsrlcIwp1ViMj2cwojXXYQ4AozlXIc5IxQF5u/VlHWDfc4sl25QFUxtleijcbbmUJPtG/owKGpRWVIDNA==,iv:NxEo+NQsE1xOuAYopiJ0ar21zGjIDXPSQJTPYBHB4a4=,tag:M2Dnq8DG5AI/XDLE7P2UMA==,type:str]
sops:
  age:
    - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiemgyQzltTXd3NXltcXB5
        VjlHVW9jOUxuRGVZZk9iVEYxbGVlNWpwZEV3Cm0yb1cvUUVUSGdmVmFjaDhXNkdH
        dzExdUtJUU9SZ3RCVnVCeDVkWTM2SGMKLS0tIGVlS0lQTHliNmdvbTZlWlFua2Z1
        R0pCaVRjSlk4TWVvR1VlVHdsVlR4NTQKHuM0bsbve/ARsvIq+PIdDnIknXT9+Dt1
        KHC4kQzMZY5wFZNAqzt5EsEpQ/FHO4bv6m4g1DF7O+jOa4V3oMtueA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T20:37:44Z"
  mac: ENC[AES256_GCM,data:Q64z9zx2FIJoT5TD9zVZzN7srHY2qyOHcS5FNX7eCL1d0kqs0Q/x3LZUe/r8kmpZcfuDXKfsgjuDfBxNse7y3TcilrmM2eK6k+MaFMXPNdb90XLcaeRldDA9zIMWgjNHny2o0y1F092Vb4NOOxBgRrQ90yIACZcRIs1mSt3EwoU=,iv:iQlrCqRPf1zCU/oNyo0aNeuKluunDbp00XHHHEi8leA=,tag:lfWdIAlYw7/a3EJ155pS4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
