---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network

components:
  - ../../components/sops
  - ../../components/alerts
resources:
  - ./namespace.yaml
  - ./cloudflare-dns/ks.yaml
  - ./cloudflare-tunnel/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./haos-external/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./truenas-external/ks.yaml
  - ./unifi-dns/ks.yaml
